travis:
  secure:
    BINSTAR_TOKEN: Va3bvcxBcMgX/iTVD2+Q4urpiP41jyPZnkUIesm52zVWKmfT2O3fOAcisbHquVN1b/4sedqZkIZPv6U2NIJJ0VjpLzKN/QjSOFLm5AyDI7CYTHYeRs/fhi+eyeRQT5UuX/8fE/kRNgN1PxGcxBg/NvN3viTsH7x1+Dh2tCzQ2v3RO2tGl5jJzwNKzbsmdw8+8m5bV52GjGAMqoGNTxo1rCEDTekqCQyHoGDlmXNBd7x2+PbpPqaV3Mpe521nJeA0C4SrTkb/aRdKz3/7jPswxv2enZLmIIFJnJNqKKn4+9MB3WkzUoxdPxEUp9Hlw/54vCgOBH2KGLHprCFxcTkBu8MToN/s3I7WQd4lqgsbxEZR0qFuW7LrMmFDebaQtin1+kQGXggpywKbUdc9VxsBmpgmxsAHv43a9mCyU9oERuzP1ainFNyjHy84Q+qaIAhRQC7FfAEKvr5B/VXwNVDuP0hUDL3TUAtiRCYekNF+pQzsIzBCh7Xo9yiY+8Losz7n76onvg6B1LJhgnfxL3psOumX7O2blXILiYBsuQJTs6D1+26h5P/XKDXZ7ZLrSb/ZCtYi7PnRVOPukN15FEBNq+7GClNjAG2rNwhRh1FHX8AeX7fixXHYqK2qtIbGjMWzi4u++UQtjqyhv0kVqHMQ9L499rWmL9hZNvP5ykCuC/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
